---
amny.com: AM New York
ap.org: Associated Press
backstage.com: Backstage
bloomberg.com: Bloomberg
chicagotribune.com: Chicago Tribune
ew.com: Entertainment Weekly
hollywoodreporter.com: Hollywood Reporter
huffingtonpost.com: Huffington Post
latimes.com: LA Times
nbcnewyork.com: NBC New York
newsday.com: Newsday
newyorker.com: New Yorker
ny1.com: NY1
nymag.com: New York Magazine
nyti.ms: New York Times
nytimes.com: New York Times
timeout.com: Time Out New York
theatermania.com: Theatermania
usatoday.com: USA Today
variety.com: Variety
vulture.com: New York Magazine
washingtonpost.com: Washington Post
